# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000014)
$foreground = rgb(FEC6BF)
$color0 = rgb(000014)
$color1 = rgb(223067)
$color2 = rgb(64217C)
$color3 = rgb(563756)
$color4 = rgb(9E1C56)
$color5 = rgb(893E46)
$color6 = rgb(BD4436)
$color7 = rgb(F5A59B)
$color8 = rgb(AC736D)
$color9 = rgb(2E4089)
$color10 = rgb(852CA5)
$color11 = rgb(734973)
$color12 = rgb(D22673)
$color13 = rgb(B7525E)
$color14 = rgb(FC5B48)
$color15 = rgb(F5A59B)
